import { useMemo, useState } from "react";

// useMemo is used to cache the values generated by more time taking functions

function findSum() {
  let sum = 0;
  for (let i = 1; i < 1000; i++) {
    sum += i;
  }
  return sum;
}

const App = () => {
  //   const sum = findSum();
  const [toggle, setToggle] = useState(true);
  const [n, setN] = useState(3);

  const sum = useMemo(() => {
    let sum = 0;
    for (let i = 1; i <= n; i++) {
      sum += i;
    }
    return sum;
  }, [n]);

  return (
    <div>
      <p>
        Sum of first {n} numbers = {sum}
      </p>
      <h1>App </h1>
      <button onClick={() => setN(n + 1)}>Increment N</button>
      <button onClick={() => setToggle(!toggle)}>Re render component</button>
    </div>
  );
};

export default App;
